version: "3"
services:
  db:
    image: mysql:latest
    container_name: docker-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "qkrwpdlr1@"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

