<script>
    import Carousel from "./Carousel.svelte";
    import banner from "./../../datas/banner";
    import Market from "./Market.svelte";
</script>

<style>
    .main__root {
        width: 100%;
        height: 100%;
        overflow: hidden;
        display: flex;
        flex-direction: column;
    }
    .main__Logo {
        width: 100vw;
        height: 100px;
        font-size: 30px;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .main__market {
        width: 100vw;
        height: 100%;
        overflow-y: scroll;
        display: flex;
        justify-content: center;
    }
    .text-focus-in {
        -webkit-animation: text-focus-in 1s
            cubic-bezier(0.55, 0.085, 0.68, 0.53) 1s both;
        animation: text-focus-in 1s cubic-bezier(0.55, 0.085, 0.68, 0.53) 1s
            both;
    }
    /* ----------------------------------------------
 * Generated by Animista on 2020-11-15 1:21:19
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
    @-webkit-keyframes text-focus-in {
        0% {
            -webkit-filter: blur(12px);
            filter: blur(12px);
            opacity: 0;
        }
        100% {
            -webkit-filter: blur(0px);
            filter: blur(0px);
            opacity: 1;
        }
    }
    @keyframes text-focus-in {
        0% {
            -webkit-filter: blur(12px);
            filter: blur(12px);
            opacity: 0;
        }
        100% {
            -webkit-filter: blur(0px);
            filter: blur(0px);
            opacity: 1;
        }
    }
</style>

<div class="main__root">
    <div class="main__Logo text-focus-in">
        <div>당신근처의 따듯한 직거래</div>
    </div>
    <Carousel elements={banner} />
    <div class="main__market">
        <Market />
    </div>
</div>
