<script>
    import { onMount } from "svelte";
    import lottie from "lottie-web";
    export let info;
    let element;
    onMount(() => {
        lottie.loadAnimation({
            container: element, // the dom element that will contain the animation
            renderer: "svg",
            loop: true,
            autoplay: true,
            path: `assets/lotties/${info.lottie}`, // the path to the animation json
        });
    });
</script>

<style>
    .market__element {
        width: 100px;
        height: 100px;
        margin: 10px;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        background-color: rgb(245, 245, 245);
        border-radius: 5px;
    }
    .lottie {
        width: 70px;
        height: 70px;
    }
    .tracking-in-expand {
        -webkit-animation: tracking-in-expand 0.2s
            cubic-bezier(0.215, 0.61, 0.355, 1) 1s both;
        animation: tracking-in-expand 0.2s cubic-bezier(0.215, 0.61, 0.355, 1)
            1s both;
    }
    /* ----------------------------------------------
 * Generated by Animista on 2020-11-15 1:28:28
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
 * ----------------------------------------
 * animation tracking-in-expand
 * ----------------------------------------
 */
    @-webkit-keyframes tracking-in-expand {
        0% {
            letter-spacing: -0.5em;
            opacity: 0;
        }
        40% {
            opacity: 0.6;
        }
        100% {
            opacity: 1;
        }
    }
    @keyframes tracking-in-expand {
        0% {
            letter-spacing: -0.5em;
            opacity: 0;
        }
        40% {
            opacity: 0.6;
        }
        100% {
            opacity: 1;
        }
    }
</style>

<div class="market__element" on:click>
    <div bind:this={element} class="lottie" />
    <div class="tracking-in-expand">{info.title}</div>
</div>
