<script>
    import Markets from "./../../datas/markets";
    import marketsellerInfo from "./../../datas/marketContent";
    import Element from "./MarketElement.svelte";
    import { push } from "svelte-spa-router";
    export let params = {};
    let marketInfo;
    let marketSellers = [];
    $: {
        marketInfo = Markets.filter(
            (item) => parseInt(item.id) === parseInt(params.id)
        )[0];
        marketSellers = marketsellerInfo.filter(
            (item) => parseInt(item.id) === parseInt(params.id)
        )[0].seller;
        console.log(marketSellers);
    }
</script>

<style>
    .market__title {
        width: 100%;
        height: 50px;
        font-size: 30px;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .wellcome__ment {
        display: flex;
        width: 100%;
        justify-content: center;
        font-size: 20px;
    }
    .focus-in-contract-bck {
        -webkit-animation: focus-in-contract-bck 1s
            cubic-bezier(0.25, 0.46, 0.45, 0.94) 0.5s both;
        animation: focus-in-contract-bck 1s cubic-bezier(0.25, 0.46, 0.45, 0.94)
            0.5s both;
    }
    .fade-in-fwd {
        -webkit-animation: fade-in-fwd 1s cubic-bezier(0.39, 0.575, 0.565, 1) 1s
            both;
        animation: fade-in-fwd 1s cubic-bezier(0.39, 0.575, 0.565, 1) 1s both;
    } /* ----------------------------------------------
/* ----------------------------------------------
 * Generated by Animista on 2020-11-15 2:18:32
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
 * ----------------------------------------
 * animation fade-in-fwd
 * ----------------------------------------
 */
    @-webkit-keyframes fade-in-fwd {
        0% {
            -webkit-transform: translateZ(-80px);
            transform: translateZ(-80px);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateZ(0);
            transform: translateZ(0);
            opacity: 1;
        }
    }
    @keyframes fade-in-fwd {
        0% {
            -webkit-transform: translateZ(-80px);
            transform: translateZ(-80px);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateZ(0);
            transform: translateZ(0);
            opacity: 1;
        }
    }
    /* ----------------------------------------------
 * Generated by Animista on 2020-11-15 1:57:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
 * ----------------------------------------
 * animation focus-in-contract-bck
 * ----------------------------------------
 */
    @-webkit-keyframes focus-in-contract-bck {
        0% {
            letter-spacing: 1em;
            -webkit-transform: translateZ(300px);
            transform: translateZ(300px);
            -webkit-filter: blur(12px);
            filter: blur(12px);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateZ(12px);
            transform: translateZ(12px);
            -webkit-filter: blur(0);
            filter: blur(0);
            opacity: 1;
        }
    }
    @keyframes focus-in-contract-bck {
        0% {
            letter-spacing: 1em;
            -webkit-transform: translateZ(300px);
            transform: translateZ(300px);
            -webkit-filter: blur(12px);
            filter: blur(12px);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateZ(12px);
            transform: translateZ(12px);
            -webkit-filter: blur(0);
            filter: blur(0);
            opacity: 1;
        }
    }
    .market__content > div {
        display: flex;
        align-items: center;
        flex-direction: column;
    }
    .market__wrap {
        width: 100vw;
        height: 100%;
        overflow-y: scroll;
    }
    .market__root {
        width: 100%;
        height: 100%;
        display: flex;
        flex-direction: column;
    }
</style>

<div class="market__root">
    <div class="market__title">{marketInfo.title}</div>
    <div class="market__wrap">
        <div class="wellcome__ment focus-in-contract-bck">
            에 오신걸 환영합니다
        </div>
        <div class="market__content">
            {#each marketSellers as marketSeller}
                <div
                    class="fade-in-fwd"
                    on:click={() => push(`/market/${params.id}/${marketSeller.sid}`)}>
                    <Element info={marketSeller} />
                </div>
            {/each}
        </div>
    </div>
</div>
