<style>
    .modal__root {
        width: 100vw;
        height: 100vh;
        position: absolute;
        top: 0;
        left: 0;
        background-color: rgba(255, 204, 0, 0.317);
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .scale-in-ver-center {
        -webkit-animation: scale-in-ver-center 0.5s
            cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
        animation: scale-in-ver-center 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
            both;
    }
    /* ----------------------------------------------
 * Generated by Animista on 2020-11-15 18:45:53
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
 * ----------------------------------------
 * animation scale-in-ver-center
 * ----------------------------------------
 */
    @-webkit-keyframes scale-in-ver-center {
        0% {
            -webkit-transform: scaleY(0);
            transform: scaleY(0);
            opacity: 1;
        }
        100% {
            -webkit-transform: scaleY(1);
            transform: scaleY(1);
            opacity: 1;
        }
    }
    @keyframes scale-in-ver-center {
        0% {
            -webkit-transform: scaleY(0);
            transform: scaleY(0);
            opacity: 1;
        }
        100% {
            -webkit-transform: scaleY(1);
            transform: scaleY(1);
            opacity: 1;
        }
    }
</style>

<div class="modal__root scale-in-ver-center">
    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/QR_code_for_mobile_English_Wikipedia.svg/440px-QR_code_for_mobile_English_Wikipedia.svg.png" alt="">
</div>
