export default [
    {
        id: 1,
        title: "무슨시장1",
        lottie: "1.json"
    }, {
        id: 2,
        title: "무슨시장2",
        lottie: "3.json"
    }, {
        id: 3,
        title: "무슨시장3",
        lottie: "2.json"
    }, {
        id: 4,
        title: "무슨시장4",
        lottie: "4.json"
    }, {
        id: 5,
        title: "무슨시장5",
        lottie: "2.json"
    }, {
        id: 6,
        title: "무슨시장6",
        lottie: "1.json"
    }, {
        id: 7,
        title: "무슨시장7",
        lottie: "4.json"
    }, {
        id: 8,
        title: "무슨시장1",
        lottie: "3.json"
    }, {
        id: 9,
        title: "무슨시장2",
        lottie: "2.json"
    }, {
        id: 10,
        title: "무슨시장3",
        lottie: "2.json"
    }, {
        id: 11,
        title: "무슨시장4",
        lottie: "4.json"
    }, {
        id: 12,
        title: "무슨시장5",
        lottie: "3.json"
    }, {
        id: 13,
        title: "무슨시장6",
        lottie: "1.json"
    }, {
        id: 14,
        title: "무슨시장7",
        lottie: "3.json"
    }, {
        id: 15,
        title: "무슨시장7",
        lottie: "3.json"
    }, {
        id: 16,
        title: "무슨시장7",
        lottie: "4.json"
    }, {
        id: 17,
        title: "무슨시장7",
        lottie: "3.json"
    }, {
        id: 18,
        title: "무슨시장7",
        lottie: "3.json"
    }, {
        id: 19,
        title: "무슨시장7",
        lottie: "2.json"
    },
]